[profile.default]
root = "."
libs = ['../../node_modules/', '../../']
tests = "./src/tests"
ffi = true
verbosity = 3
remappings = [
    '@sense-finance/v1-utils=./src',
    '@sense-finance/v1-core=../core/src',
    '@sense-finance/v1-fuse=../fuse/src',
    'solmate/=../../node_modules/solmate/src',
    '@openzeppelin/contracts=../../node_modules/@openzeppelin/contracts'
]